"""modified User model

Revision ID: 3cb0bb3fa762
Revises: 5319f054c63e
Create Date: 2021-09-08 18:23:20.080812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb0bb3fa762'
down_revision = '5319f054c63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('modified', sa.DateTime(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'modified')
    op.drop_column('users', 'created')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
